<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dt_viz</name>
  <version>1.0.0</version>

  <description>
    Digital Twin graphical interface for viewing the USV,
    AIS targets, planned defeat and collision warnings.
  </description>

  <maintainer email="seu-email@dominio.com">
    Equipe CEIA-DGS
  </maintainer>

  <license>Proprietary</license>

  <!-- Sistema de build. -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependências ROS 2. -->
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>dt_msgs</depend>
  <depend>ament_index_cpp</depend>

  <!-- pacotes internos -->
  <depend>dt_core</depend>
  <depend>dt_ros</depend>

  <!-- Dependências da interface gráfica Qt. -->
  <depend>qtbase5-dev</depend>
  
  <!-- Dependência de Testes. -->
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>